on: [pull_request]
name: Code style check & unit tests
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHP-CS-Fixer
        uses: docker://jakzal/phpqa:php7.4-alpine
        with:
          args: phpcs -n --standard=PSR12 src/

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHPUnit
        uses: docker://jakzal/phpqa:php7.4-alpine
        with:
          args: vendor/bin/phpunit
